### ISSUE TITLE
Add a WezTerm user mode for setting the `terminal` alias?

### ISSUE THREAD

**Issue by alexherbo2** [Anomalocaridid/wezterm.kak#3]
I’m not sure if it is a good idea, but can be convenient, as `new` and the windowing commands rely on `terminal`.

``` yaml
wezterm:
  v: vertical
  h: horizontal
  w: window
  t: tab
  p: popup
```

AFAIK, @vbauerster was interested in this feature for [tmux].

[tmux]: https://github.com/tmux/tmux
